include/tiny-cuda-nn/gpu_memory.h
This one fixes a memory leak using swap idiom, alternatively `free_memory()` could be called before overwriting the previous data.
=> Fixes memory leak using swap idiom

benchmarks/image/bench_ours.cu, include/tiny-cuda-nn/common.h, include/tiny-cuda-nn/cuda_graph.h, include/tiny-cuda-nn/encoding.h, include/tiny-cuda-nn/encodings/grid.h, include/tiny-cuda-nn/network_with_input_encoding.h, include/tiny-cuda-nn/networks/cutlass_mlp.h, include/tiny-cuda-nn/networks/cutlass_resnet.h, include/tiny-cuda-nn/networks/fully_fused_mlp.h, include/tiny-cuda-nn/object.h, samples/mlp_learning_an_image.cu, src/common.cu, src/cutlass_mlp.cu, src/cutlass_resnet.cu, src/fully_fused_mlp.cu, src/object.cu
- Extracts `set_params` from `initialize_params` to allow external frameworks (such as PyTorch) to supply their own parameters storage.
- This is required for PyTorch / TensorFlow bindings. #14 
- Adds compile checks for CUDA 10.2 as well as runtime checks for compute capability
=> Misc improvements

.github/workflows/main.yml, include/tiny-cuda-nn/common.h, include/tiny-cuda-nn/cutlass_matmul.h, include/tiny-cuda-nn/encodings/grid.h
This improves the performance by ~30% and reduces memory footprint significantly for GPUs with compute capability 53, 60, and 62.
Note that for compute capability 61 (GTX 1000 series) and <=52, the default remains fp32, because fp16 operations are significantly slower on those GPUs (or completely unavailable). See the [first row of this table listing fp16 vs. fp32 throughput](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#arithmetic-instructions__throughput-native-arithmetic-instructions).
=> Support fp16 on compute capabilities 53, 60, and 62

.gitignore, include/tiny-cuda-nn/config.h, include/tiny-cuda-nn/encoding.h, include/tiny-cuda-nn/encodings/grid.h, include/tiny-cuda-nn/gpu_memory.h, include/tiny-cuda-nn/network_with_input_encoding.h
This avoids a needless RM/CM conversion when the consumer (typically `NetworkWithInputEncoding`) can handle RM inputs. Consequently, the memory usage & performance of `GridEncoding` is improved. Other encodings are still to be experimented with.
=> Add support for row-major outputs of `GridEncoding`

bindings/torch/tinycudann/ops.py, bindings/torch/tinycudann/torch_bindings.cpp, include/tiny-cuda-nn/common.h, include/tiny-cuda-nn/cpp_api.h, include/tiny-cuda-nn/encodings/grid.h, include/tiny-cuda-nn/network.h, include/tiny-cuda-nn/network_with_input_encoding.h, include/tiny-cuda-nn/networks/cutlass_mlp.h, include/tiny-cuda-nn/networks/cutlass_resnet.h, include/tiny-cuda-nn/networks/fully_fused_mlp.h, include/tiny-cuda-nn/object.h, include/tiny-cuda-nn/trainer.h, src/cpp_api.cu, src/cutlass_mlp.cu, src/cutlass_resnet.cu, src/fully_fused_mlp.cu
Abstract
---
So far, __tiny-cuda-nn__ implicity assumed that each `model->forward()` call would be paired with a single `model->backward()` call in that order and with no other calls inbetween, which was inflexible at best and error prone at worst.
Due to the recently added `GPUMemoryArena`, fixing this legacy behavior is now surprisingly simple. Wider PyTorch compatibility (#39) is just the icing on the cake.
Fixes #39 
What's changed?
---
`DifferentiableObject::forward()` now returns an opaque context that must be passed to the corresponding `DifferentiableObject::backward()` call to compute gradients. See the implementation of the `Trainer` class for an example.
Multiple such contexts can exist in parallel, so there is no requirement on the order of these calls or on their …
=> Decouple `forward()` context from `Object`

bindings/torch/tinycudann/torch_bindings.cpp, include/tiny-cuda-nn/cuda_graph.h, include/tiny-cuda-nn/gpu_memory.h, include/tiny-cuda-nn/object.h, samples/mlp_learning_an_image_pytorch.py, scripts/common.py, src/cpp_api.cu
- Fixes the issue https://github.com/NVlabs/tiny-cuda-nn/issues/14#issuecomment-1039548074 mentioned by @MultiPath
- Improves/stabilizes performance by using a custom CUDA stream rather than the PyTorch-provided one (which can be the blocking global stream)
- Removes the PyEXR / OpenEXR / PIL dependencies by switching to imageio
=> Several PyTorch-related fixes

bindings/torch/setup.py, bindings/torch/tinycudann/__init__.py, bindings/torch/tinycudann/bindings.cpp, bindings/torch/tinycudann/modules.py, include/tiny-cuda-nn/common.h, include/tiny-cuda-nn/cpp_api.h, src/cpp_api.cu, src/encoding.cu
Sometimes, it can be desired to run __tiny-cuda-nn__-accelerated encodings at fp32 rather than fp16 in a PyTorch context.
This offers better numerical accuracy in rare cases at the cost of speed, while still potentially being faster than native PyTorch implementations.
(Note that __tiny-cuda-nn__'s PyTorch bindings will _not_ support fp32 MLPs (unless that's all the system can do) as those are better handled by PyTorch itself if desired.)
=> Always expose fp32 encodings in addition to fp16

include/tiny-cuda-nn/encoding.h, include/tiny-cuda-nn/encodings/composite.h, include/tiny-cuda-nn/encodings/frequency.h, include/tiny-cuda-nn/encodings/grid.h, include/tiny-cuda-nn/encodings/identity.h, include/tiny-cuda-nn/encodings/oneblob.h, include/tiny-cuda-nn/encodings/spherical_harmonics.h, include/tiny-cuda-nn/encodings/triangle_wave.h, include/tiny-cuda-nn/gpu_matrix.h, include/tiny-cuda-nn/network_with_input_encoding.h, include/tiny-cuda-nn/networks/cutlass_mlp.h, include/tiny-cuda-nn/networks/fully_fused_mlp.h, include/tiny-cuda-nn/object.h, include/tiny-cuda-nn/trainer.h, src/cutlass_mlp.cu, src/fully_fused_mlp.cu
This PR progresses __tiny-cuda-nn__'s overhaul for all differentiable components to support arbitrarily laid out data.
The last remaining component that still needs to be given support for SoA / strided data is `Loss<T>`.
Anothing (yet missing) TODO item is to extend the PyTorch bindings to exploit this functionality. Currently, PyTorch tensors are transformed to AoS layout before being passed to __tiny-cuda-nn__, which no longer has to happen.
=> Support row-major (SoA) input and outputs for all `Encoding<T>` implementations

include/tiny-cuda-nn/gpu_memory.h, scripts/test_random_input.py
when the input is random, the current version the total_n_bytes_allocated().load() can be stable, about 507510784(_x = np.random.randint(200, 800, 1)[0] , x = torch.rand([_x,100,3], dtype=torch.float, device=device) # random setting)
However, the previous version , the total_n_bytes_allocated().load() is continously increased, and there will be OOM risk, and we(with JianFei Guo) are focusing on new encoding method, and we met this problem.
=> solve OOM risk when random input is fed, details can be seen in scripts/test_random_input.py

include/tiny-cuda-nn/optimizers/ema.h
As far as i see, `m_tmp` is not used when `m_full_precision` is set to `false`.
It is reasonable to leave `m_tmp` empty for this default situation.
=> Memory optimization for EmaOptimizer

include/tiny-cuda-nn/common_device.h
Looks like your softplus backward implementation contained a mistake
=> Fixed Softplus backward

include/tiny-cuda-nn/network_with_input_encoding.h
It looks like there is a mistake in a code regarding the gradient flow. We need gradients of the network with respect to input to calculate the gradients of the encodings. This doesn't change anything currently since both cutlass and fully fused mlp ignore this flag and prepare the gradient wrp to input anyways. However, it can be an issue for somebody who would want to implement their own network.
=> fix gradient flow

include/tiny-cuda-nn/encoding.h, include/tiny-cuda-nn/encodings/composite.h, include/tiny-cuda-nn/encodings/frequency.h, include/tiny-cuda-nn/encodings/grid.h, include/tiny-cuda-nn/encodings/identity.h, include/tiny-cuda-nn/encodings/oneblob.h, include/tiny-cuda-nn/encodings/spherical_harmonics.h, include/tiny-cuda-nn/encodings/triangle_wave.h
Decouples padding from alignment, thus working around an inherent issue described in #145
=> Overhaul alignment and padding of `Encoding`

.github/workflows/main.yml, include/tiny-cuda-nn/encodings/grid.h
- Incoherent version of the prime hash (first prime isn't 1)
- Reversed prime hash (can act as a hash with "different seed" for low dimensions)
- Slow PCG32-based hash that has much better pseudorandomness
=> `GridEncoding`: add additional hash functions

include/tiny-cuda-nn/gpu_memory.h, include/tiny-cuda-nn/multi_stream.h, src/common.cu
Singleton destruction order prevents an orderly shutdown of stream-associated objects. This commit works around the issue by allocating stream-associated singletons on the heap and letting the OS clean them up after program exit.
Fixes #159
=> Fix use-after-free during program exit

bindings/torch/tinycudann/modules.py
The case is necessary because PyTorch < 1.10 and tiny-cuda-nn >= 1.5 cannot handle returning None values when doing second-order differentiation. To bypass it, create an empty tensor first, and then by checking if the tensor requires grad, convert the empty tensor into the `None` value.
Solves the initial problem in: #84 , and potential problems in: #204
=> Bypass null tensor when doing double differentiation for PyTorch < 1.10 and tiny-cuda-nn >= 1.5

DOCUMENTATION.md, include/tiny-cuda-nn/cpp_api.h, include/tiny-cuda-nn/encoding.h, include/tiny-cuda-nn/encodings/composite.h, include/tiny-cuda-nn/encodings/grid.h, include/tiny-cuda-nn/network.h, include/tiny-cuda-nn/network_with_input_encoding.h, include/tiny-cuda-nn/networks/cutlass_mlp.h, include/tiny-cuda-nn/networks/fully_fused_mlp.h, include/tiny-cuda-nn/object.h, include/tiny-cuda-nn/trainer.h, scripts/test_grid_bwdbwd.py, scripts/test_random_input.py, src/cpp_api.cu, src/cutlass_mlp.cu, src/fully_fused_mlp.cu, src/network.cu
Reduces risk of undefined behavior. Also makes two minor changes along the way:
- some components did not respect the `scale` parameter in `initialize_params`; this is now fixed
- got rid of `feedback_alignment`, which was rarely supported and did not work well in cases where it was
=> Overhaul parameter init

bindings/torch/tinycudann/modules.py
It may happen that `tinycudann_bindings` were compiled for a too modern architecture, e.g. for prebuilt docker images. In that case, no binding can be loaded and `_C` is never defined, such that the `EnvironmentError` is never reported. Defining `_C = None` should fix that code path and give a proper user-facing error message.
See also https://github.com/nerfstudio-project/nerfstudio/issues/1120 for a case where this happened.
=> Fix case where no matching tinycudann_bindings was found

bindings/torch/setup.py, bindings/torch/tinycudann/modules.py
This PR enables the `pytorch` extension to build separate kernels for each requested architecture (making use of the multi-kernel loading ability), so that it is possible to build a single wheel which is compatible with multiple compute capabilities (including some with and some without support for fused MLP).
Explicitly, to build a wheel with the package compiled for each of the compute capability 70,75,80, one can execute:
```
TCNN_CUDA_ARCHITECTURES="70,75,80" python setup.py bdist_wheel
```
It also slightly changes the name of the generated python module to be `tinycudann_bindings._{version}_C` (i.e. all binding modules are submodules of `tinycudann_bindings`) to reduce the number of packages at the root level in `site-packages`.
P.S. Thanks for the great package!
=> Enable building kernels for multiple CUDA architectures in pytorch extension

DOCUMENTATION.md
The docs did not match the implementation in `network.cu` resulting in `RuntimeError: Invalid activation name: Leaky ReLU`. This diff makes the docs match the implementation.
=> [DOCS] Fixing `Leaky ReLU` to `LeakyReLU`.

include/tiny-cuda-nn/loss.h, src/loss.cu
A small fix to allow the registrations of custom losses from outside the library.
=> Added interface to register loss from outside library

include/tiny-cuda-nn/encodings/grid.h
The runtime error message in [grid.h](https://github.com/NVlabs/tiny-cuda-nn/blob/235d1fde956dc04966940f9d1bec66aa3bdb705a/include/tiny-cuda-nn/encodings/grid.h#L1181) is misleading, as it does not reflect the current state of supported input dimensions. This PR proposes to change the error text according to the source code.
=> Fix runtime error message in grid.h

include/tiny-cuda-nn/common_host.h
See: https://stackoverflow.com/questions/76449282/workaround-for-dynamic-formatting-specs-with-fmt
fmt::format takes a consteval string when built with c++20 so wrap in fmt::runtime to allow this to compile when using c++20 or newer.
=> Fix compile error for c++20

bindings/torch/setup.py
nvcc is not always on the PATH, but it should always be in CUDA_HOME (this is where PyTorch looks for it when building the extension anyway).
Before this, if nvcc was not on the PATH, tiny-cuda-nn would attempt to build with C++14 on CUDA versions that support C++17 (and importantly, where PyTorch has dropped support for C++14).  Now tiny-cuda-nn correctly detects C++17 in those cases.
=> Look for nvcc in CUDA_HOME

src/common_host.cu
On newer CUDA versions (Linux only), cudaGetDeviceProperties became quite a bit slower. In some downstream applications, such as instant NGP, this can lead to as much as 3x slower training (!) on high-end GPUs.
To bypass the issue, this PR caches the result of cudaGetDeviceProperties such that it only needs to be called once for each device.
=> fix: CUDA API bottleneck on newer CUDA versions on Linux

.github/workflows/main.yml, bindings/torch/setup.py, bindings/torch/tinycudann/modules.py, dependencies/cuda-cmake-github-actions/scripts/actions/install_cuda_windows.ps1
10.0 blackwell b100/b200
12.0 blackwell rtx50
=> initial support blackwell

include/tiny-cuda-nn/encodings/oneblob.h
Hi @Tom94,
here's a quick fix for the padding in the OneBlob encoding. Previously, the encoding seems to overwrite some of its own data with padding when the output matrix is in SoA layout, because it starts at offset `n_dims_to_encode` rather than at `n_output_dims` (= `n_dims_to_encode * num_bins`). This PR should fix that :)
Greetings from Zürich,
– Alex
=> Fix padding in OneBlob for SoA output
